import { CheckCircle2, Download, FileSearch, Search, ShieldAlert, XCircle } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Badge, Button, EmptyState, PageHeader, Surface } from '../components/ui';
import { useWorkspace } from '../context/AppContext';
import { formatDateTime } from '../lib/format';

const actionLabels: Record<string, string> = { CRM_EXPORT: 'Экспорт CRM', CLIENT_VIEW: 'Просмотр клиента', DOCUMENT_DOWNLOAD: 'Скачивание документа', CLIENT_EXPORT_SUCCEEDED: 'Экспорт CRM', CLIENT_EXPORT_DENIED: 'Экспорт CRM' };
export function AuditPage() {
  const { audit } = useWorkspace(); const [query, setQuery] = useState(''); const [result, setResult] = useState('ALL');
  const visible = useMemo(() => audit.filter((event) => `${event.actorName} ${event.action} ${event.entityType} ${event.ip}`.toLowerCase().includes(query.toLowerCase()) && (result === 'ALL' || event.result === result)), [audit, query, result]);
  return <><PageHeader title="Журнал аудита" description="Действия с чувствительными данными" action={<Button variant="secondary" icon={Download}>Выгрузить журнал</Button>} /><Surface className="table-surface"><div className="table-toolbar"><label className="table-search"><Search size={16} /><input aria-label="Поиск событий" placeholder="Сотрудник, действие или IP" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select aria-label="Результат" value={result} onChange={(event) => setResult(event.target.value)}><option value="ALL">Все результаты</option><option value="SUCCESS">Успешно</option><option value="DENIED">Отклонено</option></select><span className="table-count">Событий: {visible.length}</span></div>{visible.length ? <div className="data-table-wrap"><table className="data-table audit-table"><thead><tr><th>Время</th><th>Сотрудник</th><th>Действие</th><th>Объект</th><th>IP-адрес</th><th>Результат</th></tr></thead><tbody>{visible.map((event) => <tr key={event.id}><td>{formatDateTime(event.createdAt)}</td><td><strong>{event.actorName}</strong></td><td><span className="audit-action"><FileSearch size={15} />{actionLabels[event.action] ?? event.action}</span></td><td>{event.entityType}{event.entityId ? ` · ${event.entityId.slice(0, 8)}` : ''}</td><td><code>{event.ip || '—'}</code></td><td><Badge tone={event.result === 'SUCCESS' ? 'success' : 'danger'}>{event.result === 'SUCCESS' ? <><CheckCircle2 size={12} />Успешно</> : <><XCircle size={12} />Отклонено</>}</Badge></td></tr>)}</tbody></table></div> : <EmptyState title="Событий нет" description="Журнал пуст для выбранных фильтров" icon={ShieldAlert} />}</Surface></>;
}
