import { ArrowLeft, BriefcaseBusiness, CalendarDays, ExternalLink, FileText, Mail, MessageSquare, Pencil, Phone, Plus, UserRound } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Navigate, useNavigate, useParams } from 'react-router-dom';
import { Avatar, Badge, Button, Dialog, EmptyState, Field, PageHeader, SectionHeader, SelectField, Surface } from '../components/ui';
import { DEMO_MODE, useWorkspace } from '../context/AppContext';
import { formatDate, formatMoney } from '../lib/format';
import type { Client } from '../types';

export function ClientPage() {
  const { id } = useParams(); const navigate = useNavigate();
  const { clients, users, deals, documents, updateClient } = useWorkspace();
  const [editOpen, setEditOpen] = useState(false); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState('');
  const client = clients.find((item) => item.id === id);
  if (!client) return <Navigate to="/crm" replace />;
  const clientDeals = deals.filter((deal) => deal.clientId === client.id);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const ownerId = String(form.get('ownerId')); setSaving(true); setFormError(''); try { await updateClient(client.id, { name: String(form.get('name')), companyName: String(form.get('companyName')), email: String(form.get('email')), phone: String(form.get('phone')), source: String(form.get('source')), status: form.get('status') as Client['status'], ownerId, ownerName: users.find((user) => user.id === ownerId)?.fullName ?? client.ownerName, notes: String(form.get('notes')) }); setEditOpen(false); } catch (reason) { setFormError(reason instanceof Error ? reason.message : 'Изменения не сохранены'); } finally { setSaving(false); } };

  return <>
    <button className="back-link" onClick={() => navigate('/crm')}><ArrowLeft size={15} />К базе клиентов</button>
    <PageHeader title={client.companyName} description={`Карточка клиента · ${client.name}`} action={<><Button variant="secondary" icon={MessageSquare} onClick={() => navigate('/messages')}>Написать</Button><Button icon={Pencil} onClick={() => setEditOpen(true)}>Редактировать</Button></>} />
    <div className="client-detail-grid">
      <Surface className="client-overview"><div className="client-hero"><span className="company-avatar company-avatar--lg"><BriefcaseBusiness size={24} /></span><div><h2>{client.companyName}</h2><span><Badge tone={client.status === 'ACTIVE' ? 'success' : client.status === 'NEW' ? 'info' : 'neutral'}>{client.status === 'ACTIVE' ? 'Активный' : client.status === 'NEW' ? 'Новый' : 'На паузе'}</Badge><small>Источник: {client.source}</small></span></div></div><dl className="detail-list"><div><dt><UserRound size={15} />Контакт</dt><dd>{client.name}</dd></div><div><dt><Mail size={15} />Email</dt><dd><a href={`mailto:${client.email}`}>{client.email}</a></dd></div><div><dt><Phone size={15} />Телефон</dt><dd><a href={`tel:${client.phone}`}>{client.phone}</a></dd></div><div><dt><UserRound size={15} />Ответственный</dt><dd><Avatar name={client.ownerName} size="sm" />{client.ownerName}</dd></div></dl><div className="notes-block"><span>Заметка</span><p>{client.notes || 'Нет заметок'}</p></div></Surface>
      <Surface className="client-deals"><SectionHeader title="Сделки" meta={<Badge tone="info">{clientDeals.length}</Badge>} action={<Button variant="secondary" icon={Plus} onClick={() => navigate('/sales')}>Новая</Button>} />{clientDeals.length ? <div className="deal-list">{clientDeals.map((deal) => <button key={deal.id} onClick={() => navigate('/sales')}><span><strong>{deal.title}</strong><small><CalendarDays size={13} /> до {formatDate(deal.expectedCloseAt)}</small></span><span><strong>{formatMoney(deal.value, deal.currency)}</strong><Badge tone={deal.probability >= 80 ? 'success' : 'warning'}>{deal.probability}%</Badge></span></button>)}</div> : <EmptyState title="Сделок пока нет" description="Создайте первую сделку для этого клиента" icon={BriefcaseBusiness} />}</Surface>
      <Surface className="client-history"><SectionHeader title="История" />{DEMO_MODE ? <div className="timeline"><article><i /><span><strong>Карточка обновлена</strong><small>Изменён следующий шаг · сегодня, 10:24</small></span></article><article><i /><span><strong>Входящее письмо</strong><small>«Re: Материалы к встрече» · вчера</small></span></article><article><i /><span><strong>Создана сделка</strong><small>{clientDeals[0]?.title ?? 'Новая возможность'} · 12 августа</small></span></article></div> : <EmptyState title="История пуста" description="Новые комментарии и события появятся здесь" icon={MessageSquare} />}</Surface>
      <Surface className="client-files"><SectionHeader title="Файлы" action={<button className="text-button" onClick={() => navigate('/documents')}>Все документы <ExternalLink size={13} /></button>} /><div className="compact-files">{documents.slice(0, 3).map((document) => <button key={document.id} onClick={() => navigate('/documents')}><span className="file-icon"><FileText size={17} /></span><span><strong>{document.title}</strong><small>Версия {document.version} · {formatDate(document.updatedAt)}</small></span></button>)}</div></Surface>
    </div>
    <Dialog open={editOpen} title="Редактировать клиента" onClose={() => setEditOpen(false)} size="lg" footer={<><Button variant="secondary" onClick={() => setEditOpen(false)}>Отмена</Button><Button form="edit-client" type="submit" disabled={saving}>{saving ? 'Сохраняем…' : 'Сохранить'}</Button></>}><form id="edit-client" className="form-grid" onSubmit={(event) => void save(event)}><Field label="Компания"><input name="companyName" defaultValue={client.companyName} required /></Field><Field label="Контакт"><input name="name" defaultValue={client.name} required /></Field><Field label="Email"><input name="email" type="email" defaultValue={client.email} required /></Field><Field label="Телефон"><input name="phone" defaultValue={client.phone} required /></Field><Field label="Источник"><input name="source" defaultValue={client.source} required /></Field><SelectField label="Статус" name="status" defaultValue={client.status}><option value="NEW">Новый</option><option value="ACTIVE">Активный</option><option value="PAUSED">На паузе</option></SelectField><SelectField label="Ответственный" name="ownerId" defaultValue={client.ownerId}>{users.map((user) => <option value={user.id} key={user.id}>{user.fullName}</option>)}</SelectField><Field label="Заметка" className="field--wide"><textarea name="notes" rows={4} defaultValue={client.notes} /></Field>{formError && <div className="form-error field--wide" role="alert">{formError}</div>}</form></Dialog>
  </>;
}
