import { Download, Eye, File, FileArchive, FileImage, FileSpreadsheet, FileText, Folder, FolderOpen, Grid2X2, List, MoreHorizontal, Plus, Search, Shield, UploadCloud } from 'lucide-react';
import { useMemo, useRef, useState, type FormEvent } from 'react';
import { api } from '../lib/api';
import { Badge, Button, Dialog, EmptyState, Field, IconButton, PageHeader, Segmented, SelectField, Surface } from '../components/ui';
import { DEMO_MODE, useAuth, useWorkspace } from '../context/AppContext';
import { fileSize, formatDateTime } from '../lib/format';
import type { CompanyDocument } from '../types';

const visibility = { COMPANY: 'Вся компания', DEPARTMENT: 'Отдел', PRIVATE: 'Личный' } as const;
const fileIcon = (mime: string) => mime.includes('image') ? FileImage : mime.includes('sheet') || mime.includes('excel') ? FileSpreadsheet : mime.includes('zip') ? FileArchive : mime.includes('pdf') || mime.includes('word') ? FileText : File;

export function DocumentsPage() {
  const { session } = useAuth(); const { documents, addDocument } = useWorkspace();
  const [folder, setFolder] = useState('Все файлы'); const [query, setQuery] = useState(''); const [view, setView] = useState<'list' | 'grid'>('list');
  const [uploadOpen, setUploadOpen] = useState(false); const [selected, setSelected] = useState<CompanyDocument | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const inputRef = useRef<HTMLInputElement>(null);
  const folders = useMemo(() => ['Все файлы', ...Array.from(new Set(documents.map((document) => document.folder)))], [documents]);
  const visible = useMemo(() => documents.filter((document) => (folder === 'Все файлы' || document.folder === folder) && `${document.title} ${document.fileName}`.toLowerCase().includes(query.toLowerCase())), [documents, folder, query]);
  const upload = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const file = form.get('file'); if (!(file instanceof File) || !file.size) return; setSaving(true); setError(''); try { await addDocument(file, String(form.get('folder')), form.get('visibility') as CompanyDocument['visibility']); setUploadOpen(false); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Загрузка не выполнена'); } finally { setSaving(false); } };
  const download = async (document: CompanyDocument) => { setError(''); try { const blob = DEMO_MODE && session!.accessToken.startsWith('demo-') ? new Blob([`Atlas demo: ${document.title}`], { type: 'text/plain' }) : await api.download(`/documents/${document.id}/download`); const link = window.document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = document.fileName; link.click(); URL.revokeObjectURL(link.href); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Файл недоступен'); } };

  return <>
    <PageHeader title="Документы" description={`${documents.length} файлов в доступных разделах`} action={<Button icon={UploadCloud} onClick={() => setUploadOpen(true)}>Загрузить</Button>} />
    {error && <div className="notice notice--danger" role="alert">{error}<button onClick={() => setError('')}>Закрыть</button></div>}
    <div className="documents-layout">
      <aside className="folder-nav"><header><span>Папки</span><IconButton label="Создать папку" icon={Plus} /></header>{folders.map((item) => <button key={item} className={folder === item ? 'is-active' : ''} onClick={() => setFolder(item)}>{item === 'Все файлы' ? <FolderOpen size={17} /> : <Folder size={17} />}<span>{item}</span><small>{item === 'Все файлы' ? documents.length : documents.filter((document) => document.folder === item).length}</small></button>)}</aside>
      <Surface className="document-surface"><div className="table-toolbar"><label className="table-search"><Search size={16} /><input aria-label="Поиск документов" placeholder="Поиск по названию" value={query} onChange={(event) => setQuery(event.target.value)} /></label><Segmented value={view} label="Вид документов" options={[{ value: 'list', label: 'Список' }, { value: 'grid', label: 'Плитка' }]} onChange={setView} /></div>{visible.length ? view === 'list' ? <div className="data-table-wrap"><table className="data-table document-table"><thead><tr><th>Название</th><th>Папка</th><th>Доступ</th><th>Версия</th><th>Изменён</th><th aria-label="Действия" /></tr></thead><tbody>{visible.map((document) => { const Icon = fileIcon(document.mimeType); return <tr key={document.id}><td><button className="document-name" onClick={() => setSelected(document)}><span className="file-icon"><Icon size={18} /></span><span><strong>{document.title}</strong><small>{document.fileName} · {fileSize(document.sizeBytes)}</small></span></button></td><td>{document.folder}</td><td><Badge tone={document.visibility === 'PRIVATE' ? 'warning' : document.visibility === 'DEPARTMENT' ? 'info' : 'neutral'}>{visibility[document.visibility]}</Badge></td><td>v{document.version}</td><td><span>{formatDateTime(document.updatedAt)}</span><small className="table-subline">{document.uploadedBy}</small></td><td><div className="row-actions"><IconButton label="Предпросмотр" icon={Eye} onClick={() => setSelected(document)} /><IconButton label="Скачать" icon={Download} onClick={() => void download(document)} /></div></td></tr>; })}</tbody></table></div> : <div className="document-grid">{visible.map((document) => { const Icon = fileIcon(document.mimeType); return <article key={document.id}><button className="document-grid__main" onClick={() => setSelected(document)}><span className="file-icon file-icon--lg"><Icon size={24} /></span><strong>{document.title}</strong><small>{document.fileName}</small></button><footer><span>{fileSize(document.sizeBytes)} · v{document.version}</span><IconButton label="Скачать" icon={Download} onClick={() => void download(document)} /></footer></article>; })}</div> : <EmptyState title="Файлы не найдены" description="Измените запрос или загрузите документ" icon={FileText} action={<Button icon={UploadCloud} onClick={() => setUploadOpen(true)}>Загрузить</Button>} />}</Surface>
    </div>
    <Dialog open={uploadOpen} title="Загрузка документа" description="PDF, DOCX, XLSX или изображение" onClose={() => setUploadOpen(false)} footer={<><Button variant="secondary" onClick={() => setUploadOpen(false)}>Отмена</Button><Button form="upload-form" type="submit" disabled={saving}>{saving ? 'Загружаем…' : 'Загрузить'}</Button></>}><form id="upload-form" className="upload-form" onSubmit={(event) => void upload(event)}><button type="button" className="drop-zone" onClick={() => inputRef.current?.click()}><UploadCloud size={26} /><strong>Выберите файл</strong><span>до 20 МБ</span></button><input ref={inputRef} name="file" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,image/*" required /><Field label="Папка"><input name="folder" list="folder-list" defaultValue={folders[1] ?? 'Общие'} required /><datalist id="folder-list">{folders.slice(1).map((item) => <option value={item} key={item} />)}</datalist></Field><SelectField label="Доступ" name="visibility" defaultValue="COMPANY"><option value="COMPANY">Вся компания</option><option value="DEPARTMENT">Только отдел</option><option value="PRIVATE">Только я</option></SelectField></form></Dialog>
    <Dialog open={Boolean(selected)} title={selected?.title ?? ''} description={selected ? `${selected.fileName} · версия ${selected.version}` : undefined} onClose={() => setSelected(null)} footer={selected && <><Button variant="secondary" onClick={() => setSelected(null)}>Закрыть</Button><Button icon={Download} onClick={() => void download(selected)}>Скачать</Button></>}><div className="file-preview"><span className="file-icon file-icon--xl">{selected && (() => { const Icon = fileIcon(selected.mimeType); return <Icon size={34} />; })()}</span><dl><div><dt>Папка</dt><dd>{selected?.folder}</dd></div><div><dt>Размер</dt><dd>{selected && fileSize(selected.sizeBytes)}</dd></div><div><dt>Доступ</dt><dd>{selected && visibility[selected.visibility]}</dd></div><div><dt>Загрузил</dt><dd>{selected?.uploadedBy}</dd></div></dl></div></Dialog>
  </>;
}
