import { Bell, Check, KeyRound, LockKeyhole, MonitorCheck, Save, ShieldCheck, UserRound } from 'lucide-react';
import { useState } from 'react';
import { Avatar, Badge, Button, Field, Meter, PageHeader, SectionHeader, Surface } from '../components/ui';
import { useAuth } from '../context/AppContext';
import { formatDate, roleLabel } from '../lib/format';

export function ProfilePage() {
  const { session, consent } = useAuth(); const user = session!.user; const [consenting, setConsenting] = useState(false); const [saved, setSaved] = useState(false);
  const accept = async () => { setConsenting(true); try { await consent(); } finally { setConsenting(false); } };
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 1800); };
  return <><PageHeader title="Профиль" description="Учётная запись и личные настройки" action={<Button icon={saved ? Check : Save} onClick={save}>{saved ? 'Сохранено' : 'Сохранить'}</Button>} /><div className="profile-layout"><Surface className="profile-identity"><div className="profile-identity__head"><Avatar name={user.fullName} online size="lg" /><div><h2>{user.fullName}</h2><span>@{user.username}</span><Badge tone="info">{roleLabel[user.role]}</Badge></div></div><dl><div><dt>Должность</dt><dd>{user.jobTitle}</dd></div><div><dt>Отдел</dt><dd>{user.department}</dd></div><div><dt>Специализация</dt><dd>{user.specialty ?? 'Не указана'}</dd></div>{user.jobDescription && <div><dt>Должностная инструкция</dt><dd>{user.jobDescription}</dd></div>}</dl><div className="profile-rating"><span><strong>{user.rating}</strong><small>рейтинг</small></span><Meter value={user.rating} /></div></Surface><div className="profile-settings"><Surface><SectionHeader title="Личные настройки" /><div className="settings-form"><Field label="Полное имя"><input defaultValue={user.fullName} /></Field><Field label="Рабочий логин"><input defaultValue={user.username} disabled /></Field><label className="switch-row"><span><Bell size={17} /><span><strong>Уведомления в интерфейсе</strong><small>Задачи, сделки и системные события</small></span></span><input type="checkbox" defaultChecked /></label><label className="switch-row"><span><MonitorCheck size={17} /><span><strong>Показывать статус присутствия</strong><small>Статус обновляется при активной сессии</small></span></span><input type="checkbox" defaultChecked /></label></div></Surface><Surface className="consent-panel"><SectionHeader title="Согласие на мониторинг" meta={user.monitoringConsentAt ? <Badge tone="success">Принято</Badge> : <Badge tone="warning">Требуется</Badge>} /><p>Компания фиксирует статус присутствия, метаданные доступа к CRM, системные события и сроки задач. Содержание личной переписки не анализируется.</p><div className="consent-meta"><ShieldCheck size={18} /><span><strong>Политика 2026-01</strong><small>{user.monitoringConsentAt ? `Согласие дано ${formatDate(user.monitoringConsentAt)}` : 'Ознакомьтесь и подтвердите согласие'}</small></span></div>{!user.monitoringConsentAt && <Button icon={Check} disabled={consenting} onClick={() => void accept()}>{consenting ? 'Подтверждаем…' : 'Принять политику'}</Button>}</Surface><Surface><SectionHeader title="Безопасность" /><div className="security-rows"><div><span className="settings-icon"><LockKeyhole size={17} /></span><span><strong>Пароль</strong><small>Рекомендуется менять каждые 90 дней</small></span><Button variant="secondary">Изменить</Button></div><div><span className="settings-icon"><KeyRound size={17} /></span><span><strong>Двухфакторная аутентификация</strong><small>Дополнительная защита входа</small></span><Button variant="secondary">Настроить</Button></div></div></Surface></div></div></>;
}
