import { BarChart3, CalendarRange, CheckCircle2, Clock3, FileBarChart, Plus, RefreshCw, Users } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Badge, Button, Dialog, EmptyState, Field, PageHeader, SelectField, Surface } from '../components/ui';
import { useWorkspace } from '../context/AppContext';
import { formatDate } from '../lib/format';
import type { Report } from '../types';

const metricOptions = [
  ['deals', 'Количество сделок'], ['conversion', 'Конверсия воронки'], ['kpi', 'Выполнение KPI'], ['tasks', 'Задачи в срок'], ['attendance', 'Присутствие'],
] as const;
const metricLabels = Object.fromEntries(metricOptions) as Record<Report['metrics'][number], string>;
const scheduleLabels = { ONCE: 'Однократно', DAILY: 'Ежедневно', WEEKLY: 'Еженедельно', MONTHLY: 'Ежемесячно' } as const;

export function ReportsPage() {
  const { reports, users, addReport } = useWorkspace(); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const targetUserId = String(form.get('targetUserId')); const metrics = form.getAll('metrics').map(String) as Report['metrics']; if (!metrics.length) { setError('Выберите хотя бы одну метрику'); return; } setSaving(true); setError(''); try { await addReport({ name: String(form.get('name')), targetUserId, targetUserName: users.find((user) => user.id === targetUserId)?.fullName ?? '', metrics, periodStart: String(form.get('periodStart')), periodEnd: String(form.get('periodEnd')), schedule: form.get('schedule') as Report['schedule'] }); setOpen(false); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Отчёт не создан'); } finally { setSaving(false); } };
  return <>
    <PageHeader title="Отчёты" description="Сводки по команде, продажам и KPI" action={<Button icon={Plus} onClick={() => setOpen(true)}>Создать отчёт</Button>} />
    <div className="report-summary"><Surface><span><FileBarChart size={19} /></span><div><strong>{reports.length}</strong><small>всего отчётов</small></div></Surface><Surface><span><RefreshCw size={19} /></span><div><strong>{reports.filter((report) => report.schedule !== 'ONCE').length}</strong><small>по расписанию</small></div></Surface><Surface><span><CheckCircle2 size={19} /></span><div><strong>{reports.filter((report) => report.status === 'READY').length}</strong><small>готовы</small></div></Surface></div>
    <Surface className="report-list"><div className="table-toolbar"><strong>Сохранённые отчёты</strong><select aria-label="Периодичность"><option>Все расписания</option><option>Еженедельно</option><option>Ежемесячно</option></select></div>{reports.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Отчёт</th><th>Область</th><th>Метрики</th><th>Период</th><th>Расписание</th><th>Статус</th></tr></thead><tbody>{reports.map((report) => <tr key={report.id}><td><span className="report-name"><FileBarChart size={17} /><strong>{report.name}</strong></span></td><td>{report.targetUserName}</td><td><span className="metric-tags">{report.metrics.slice(0, 3).map((metric) => <Badge key={metric}>{metricLabels[metric] ?? metric}</Badge>)}</span></td><td>{formatDate(report.periodStart)} — {formatDate(report.periodEnd)}</td><td>{scheduleLabels[report.schedule]}</td><td><Badge tone={report.status === 'READY' ? 'success' : report.status === 'FAILED' ? 'danger' : 'warning'}>{report.status === 'READY' ? 'Готов' : report.status === 'FAILED' ? 'Ошибка' : 'Формируется'}</Badge></td></tr>)}</tbody></table></div> : <EmptyState title="Отчётов пока нет" description="Соберите первый отчёт по нужным метрикам" icon={BarChart3} action={<Button icon={Plus} onClick={() => setOpen(true)}>Создать отчёт</Button>} />}</Surface>
    <Dialog open={open} title="Конструктор отчёта" description="Выберите область, период и показатели" size="lg" onClose={() => setOpen(false)} footer={<><Button variant="secondary" onClick={() => setOpen(false)}>Отмена</Button><Button type="submit" form="report-form" disabled={saving}>{saving ? 'Создаём…' : 'Создать отчёт'}</Button></>}><form id="report-form" className="form-grid report-form" onSubmit={(event) => void save(event)}><Field label="Название" className="field--wide"><input name="name" required placeholder="Например, Итоги продаж за август" /></Field><SelectField label="Сотрудник" name="targetUserId" required defaultValue={users[0]?.id}><option value="" disabled>Выберите сотрудника</option>{users.map((user) => <option value={user.id} key={user.id}>{user.fullName}</option>)}</SelectField><SelectField label="Периодичность" name="schedule" defaultValue="WEEKLY"><option value="ONCE">Однократно</option><option value="DAILY">Ежедневно</option><option value="WEEKLY">Еженедельно</option><option value="MONTHLY">Ежемесячно</option></SelectField><Field label="Начало периода"><input name="periodStart" type="date" defaultValue={new Date(Date.now() - 7 * 86400000).toISOString().slice(0, 10)} required /></Field><Field label="Конец периода"><input name="periodEnd" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></Field><fieldset className="metric-checks"><legend>Метрики</legend>{metricOptions.map(([value, label]) => <label key={value}><input type="checkbox" name="metrics" value={value} defaultChecked={['deals', 'conversion', 'kpi'].includes(value)} /><span>{label}</span></label>)}</fieldset>{error && <div className="form-error field--wide" role="alert">{error}</div>}</form></Dialog>
  </>;
}
