import { CalendarDays, GripVertical, MoreHorizontal, Plus, Settings2, SlidersHorizontal, UserRound } from 'lucide-react';
import { useMemo, useState, type DragEvent, type FormEvent } from 'react';
import { Badge, Button, Dialog, EmptyState, Field, IconButton, PageHeader, SelectField } from '../components/ui';
import { useAuth, useWorkspace } from '../context/AppContext';
import { formatDate, formatMoney } from '../lib/format';
import type { Deal, DealStage } from '../types';

export function SalesPage() {
  const { session } = useAuth();
  const { deals, stages, clients, users, moveDeal, addDeal, addStage } = useWorkspace();
  const [dealOpen, setDealOpen] = useState(false); const [stageOpen, setStageOpen] = useState(false);
  const [owner, setOwner] = useState('ALL'); const [saving, setSaving] = useState(false);
  const [dragged, setDragged] = useState<string | null>(null);
  const [error, setError] = useState('');
  const canConfigure = session!.user.role !== 'EMPLOYEE';
  const visibleDeals = useMemo(() => deals.filter((deal) => owner === 'ALL' || deal.ownerId === owner), [deals, owner]);
  const total = visibleDeals.filter((deal) => !stages.find((stage) => stage.key === deal.stage)?.isClosed).reduce((sum, deal) => sum + deal.value, 0);

  const changeDeal = async (id: string, stage: string) => { setError(''); try { await moveDeal(id, stage); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Сделка не перемещена'); } };
  const drop = (event: DragEvent, stage: string) => { event.preventDefault(); if (dragged) void changeDeal(dragged, stage); setDragged(null); };
  const saveDeal = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const clientId = String(form.get('clientId')); const ownerId = String(form.get('ownerId')); setSaving(true); setError(''); try { await addDeal({ clientId, title: String(form.get('title')), companyName: clients.find((client) => client.id === clientId)?.companyName ?? '', ownerId, ownerName: users.find((user) => user.id === ownerId)?.fullName ?? session!.user.fullName, stage: String(form.get('stage')), value: Number(form.get('value')), currency: 'UAH', probability: Number(form.get('probability')), expectedCloseAt: new Date(String(form.get('expectedCloseAt'))).toISOString() }); setDealOpen(false); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Сделка не создана'); } finally { setSaving(false); } };
  const saveStage = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get('name')); setSaving(true); setError(''); try { await addStage({ key: name.toUpperCase().replace(/[^A-ZА-Я0-9]+/gi, '_').replace(/[А-Я]/g, '') || `STAGE_${Date.now()}`, name, color: String(form.get('color')), sortOrder: stages.length ? Math.max(...stages.map((stage) => stage.sortOrder)) + 10 : 10, isClosed: false }); setStageOpen(false); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Этап не добавлен'); } finally { setSaving(false); } };

  return <>
    <PageHeader title="Воронка продаж" description={`${visibleDeals.length} сделок · ${formatMoney(total)} в активной работе`} action={<>{session!.user.role !== 'EMPLOYEE' && <label className="compact-select"><UserRound size={15} /><select aria-label="Ответственный" value={owner} onChange={(event) => setOwner(event.target.value)}><option value="ALL">Вся команда</option>{users.map((user) => <option value={user.id} key={user.id}>{user.fullName}</option>)}</select></label>}{canConfigure && <IconButton label="Настроить этапы" icon={Settings2} onClick={() => setStageOpen(true)} />}<Button icon={Plus} onClick={() => setDealOpen(true)}>Новая сделка</Button></>} />
    {error && <div className="notice notice--danger" role="alert">{error}<button onClick={() => setError('')}>Закрыть</button></div>}
    {stages.length ? <div className="kanban kanban--sales">{stages.map((stage) => { const items = visibleDeals.filter((deal) => deal.stage === stage.key); const sum = items.reduce((value, deal) => value + deal.value, 0); return <section className="kanban-column" key={stage.key} onDragOver={(event) => event.preventDefault()} onDrop={(event) => drop(event, stage.key)}><header style={{ '--stage-color': stage.color } as React.CSSProperties}><div><i /><strong>{stage.name}</strong><Badge>{items.length}</Badge></div><span>{formatMoney(sum)}</span></header><div className="kanban-column__body">{items.map((deal) => <DealCard key={deal.id} deal={deal} stages={stages} onDrag={() => setDragged(deal.id)} onMove={(next) => void changeDeal(deal.id, next)} />)}{!items.length && <div className="kanban-empty">Нет сделок</div>}<button className="kanban-add" onClick={() => setDealOpen(true)}><Plus size={15} />Добавить сделку</button></div></section>; })}</div> : <EmptyState title="Этапы воронки не настроены" description="Добавьте первый этап, чтобы начать работу со сделками" icon={SlidersHorizontal} action={canConfigure ? <Button icon={Plus} onClick={() => setStageOpen(true)}>Добавить этап</Button> : undefined} />}
    <Dialog open={dealOpen} title="Новая сделка" description="Привяжите сделку к клиенту и ответственному" size="lg" onClose={() => setDealOpen(false)} footer={<><Button variant="secondary" onClick={() => setDealOpen(false)}>Отмена</Button><Button type="submit" form="deal-form" disabled={saving}>{saving ? 'Сохраняем…' : 'Создать сделку'}</Button></>}><form id="deal-form" className="form-grid" onSubmit={(event) => void saveDeal(event)}><Field label="Название" className="field--wide"><input name="title" required placeholder="Предмет сделки" /></Field><SelectField label="Клиент" name="clientId" required><option value="">Выберите клиента</option>{clients.map((client) => <option value={client.id} key={client.id}>{client.companyName}</option>)}</SelectField><SelectField label="Ответственный" name="ownerId" defaultValue={session!.user.id}>{users.map((user) => <option value={user.id} key={user.id}>{user.fullName}</option>)}</SelectField><SelectField label="Этап" name="stage" defaultValue={stages[0]?.key}>{stages.map((stage) => <option value={stage.key} key={stage.key}>{stage.name}</option>)}</SelectField><Field label="Сумма, ₴"><input name="value" type="number" min="0" step="1000" required /></Field><Field label="Вероятность, %"><input name="probability" type="number" min="0" max="100" defaultValue="30" required /></Field><Field label="Ожидаемое закрытие"><input name="expectedCloseAt" type="date" defaultValue={new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10)} required /></Field></form></Dialog>
    <Dialog open={stageOpen} title="Новый этап" description="Он появится в конце текущей воронки" onClose={() => setStageOpen(false)} footer={<><Button variant="secondary" onClick={() => setStageOpen(false)}>Отмена</Button><Button type="submit" form="stage-form" disabled={saving}>Добавить</Button></>}><form id="stage-form" className="form-grid" onSubmit={(event) => void saveStage(event)}><Field label="Название" className="field--wide"><input name="name" required placeholder="Например, Согласование" /></Field><Field label="Цвет"><input name="color" type="color" defaultValue="#398078" /></Field></form></Dialog>
  </>;
}

function DealCard({ deal, stages, onDrag, onMove }: { deal: Deal; stages: DealStage[]; onDrag: () => void; onMove: (stage: string) => void }) {
  return <article className="kanban-card" draggable onDragStart={(event) => { event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', deal.id); onDrag(); }}><div className="kanban-card__top"><span className="drag-handle"><GripVertical size={15} /></span><small>{deal.companyName}</small><IconButton label="Действия со сделкой" icon={MoreHorizontal} /></div><strong>{deal.title}</strong><div className="deal-value"><b>{formatMoney(deal.value, deal.currency)}</b><span>{deal.probability}%</span></div><div className="kanban-card__meta"><span><CalendarDays size={13} />{formatDate(deal.expectedCloseAt)}</span><span><UserRound size={13} />{deal.ownerName.split(' ')[0]}</span></div><select className="card-move-select" aria-label={`Переместить сделку ${deal.title}`} value={deal.stage} onChange={(event) => onMove(event.target.value)}>{stages.map((stage) => <option key={stage.key} value={stage.key}>{stage.name}</option>)}</select></article>;
}
